version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - .:/var/www/html
      # serve php file
    ports:
      - 81:80
  # Server name
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    # Phpmyadmin port
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
